// Code generated by protoc-gen-go.
// source: event.proto
// DO NOT EDIT!

/*
Package pb_event is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	User
	Header
	Event
	MarioEvents
*/
package pb_event

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type User struct {
	UserUniqueId     *string `protobuf:"bytes,1,req,name=user_unique_id" json:"user_unique_id,omitempty"`
	UserType         *uint32 `protobuf:"varint,2,opt,name=user_type" json:"user_type,omitempty"`
	UserId           *uint64 `protobuf:"varint,3,opt,name=user_id" json:"user_id,omitempty"`
	UserIsAuth       *bool   `protobuf:"varint,4,opt,name=user_is_auth" json:"user_is_auth,omitempty"`
	UserIsLogin      *bool   `protobuf:"varint,5,opt,name=user_is_login" json:"user_is_login,omitempty"`
	DeviceId         *uint64 `protobuf:"varint,6,opt,name=device_id" json:"device_id,omitempty"`
	WebId            *uint64 `protobuf:"varint,7,opt,name=web_id" json:"web_id,omitempty"`
	IpAddrId         *uint64 `protobuf:"varint,8,opt,name=ip_addr_id" json:"ip_addr_id,omitempty"`
	Ssid             *string `protobuf:"bytes,9,opt,name=ssid" json:"ssid,omitempty"`
	OpenUdid         *string `protobuf:"bytes,10,opt,name=open_udid" json:"open_udid,omitempty"`
	Udid             *string `protobuf:"bytes,11,opt,name=udid" json:"udid,omitempty"`
	Idfa             *string `protobuf:"bytes,12,opt,name=idfa" json:"idfa,omitempty"`
	Idfv             *string `protobuf:"bytes,13,opt,name=idfv" json:"idfv,omitempty"`
	BuildSerial      *string `protobuf:"bytes,14,opt,name=build_serial" json:"build_serial,omitempty"`
	ClientUdid       *string `protobuf:"bytes,15,opt,name=client_udid" json:"client_udid,omitempty"`
	Mc               *string `protobuf:"bytes,16,opt,name=mc" json:"mc,omitempty"`
	SerialNumber     *string `protobuf:"bytes,17,opt,name=serial_number" json:"serial_number,omitempty"`
	IsUpgradeUser    *bool   `protobuf:"varint,18,opt,name=is_upgrade_user" json:"is_upgrade_user,omitempty"`
	Oaid             *string `protobuf:"bytes,19,opt,name=oaid" json:"oaid,omitempty"`
	Cdid             *string `protobuf:"bytes,20,opt,name=cdid" json:"cdid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetUserUniqueId() string {
	if m != nil && m.UserUniqueId != nil {
		return *m.UserUniqueId
	}
	return ""
}

func (m *User) GetUserType() uint32 {
	if m != nil && m.UserType != nil {
		return *m.UserType
	}
	return 0
}

func (m *User) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *User) GetUserIsAuth() bool {
	if m != nil && m.UserIsAuth != nil {
		return *m.UserIsAuth
	}
	return false
}

func (m *User) GetUserIsLogin() bool {
	if m != nil && m.UserIsLogin != nil {
		return *m.UserIsLogin
	}
	return false
}

func (m *User) GetDeviceId() uint64 {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return 0
}

func (m *User) GetWebId() uint64 {
	if m != nil && m.WebId != nil {
		return *m.WebId
	}
	return 0
}

func (m *User) GetIpAddrId() uint64 {
	if m != nil && m.IpAddrId != nil {
		return *m.IpAddrId
	}
	return 0
}

func (m *User) GetSsid() string {
	if m != nil && m.Ssid != nil {
		return *m.Ssid
	}
	return ""
}

func (m *User) GetOpenUdid() string {
	if m != nil && m.OpenUdid != nil {
		return *m.OpenUdid
	}
	return ""
}

func (m *User) GetUdid() string {
	if m != nil && m.Udid != nil {
		return *m.Udid
	}
	return ""
}

func (m *User) GetIdfa() string {
	if m != nil && m.Idfa != nil {
		return *m.Idfa
	}
	return ""
}

func (m *User) GetIdfv() string {
	if m != nil && m.Idfv != nil {
		return *m.Idfv
	}
	return ""
}

func (m *User) GetBuildSerial() string {
	if m != nil && m.BuildSerial != nil {
		return *m.BuildSerial
	}
	return ""
}

func (m *User) GetClientUdid() string {
	if m != nil && m.ClientUdid != nil {
		return *m.ClientUdid
	}
	return ""
}

func (m *User) GetMc() string {
	if m != nil && m.Mc != nil {
		return *m.Mc
	}
	return ""
}

func (m *User) GetSerialNumber() string {
	if m != nil && m.SerialNumber != nil {
		return *m.SerialNumber
	}
	return ""
}

func (m *User) GetIsUpgradeUser() bool {
	if m != nil && m.IsUpgradeUser != nil {
		return *m.IsUpgradeUser
	}
	return false
}

func (m *User) GetOaid() string {
	if m != nil && m.Oaid != nil {
		return *m.Oaid
	}
	return ""
}

func (m *User) GetCdid() string {
	if m != nil && m.Cdid != nil {
		return *m.Cdid
	}
	return ""
}

type Header struct {
	Headers           *string  `protobuf:"bytes,1,opt,name=headers" json:"headers,omitempty"`
	AppId             *uint32  `protobuf:"varint,2,req,name=app_id" json:"app_id,omitempty"`
	AppName           *string  `protobuf:"bytes,3,opt,name=app_name" json:"app_name,omitempty"`
	AppInstallId      *uint64  `protobuf:"varint,4,opt,name=app_install_id" json:"app_install_id,omitempty"`
	AppPackage        *string  `protobuf:"bytes,5,opt,name=app_package" json:"app_package,omitempty"`
	AppChannel        *string  `protobuf:"bytes,6,opt,name=app_channel" json:"app_channel,omitempty"`
	AppVersion        *string  `protobuf:"bytes,7,opt,name=app_version" json:"app_version,omitempty"`
	OsName            *string  `protobuf:"bytes,8,opt,name=os_name" json:"os_name,omitempty"`
	OsVersion         *string  `protobuf:"bytes,9,opt,name=os_version" json:"os_version,omitempty"`
	DeviceModel       *string  `protobuf:"bytes,10,opt,name=device_model" json:"device_model,omitempty"`
	AbClient          *string  `protobuf:"bytes,11,opt,name=ab_client" json:"ab_client,omitempty"`
	AbVersion         *string  `protobuf:"bytes,12,opt,name=ab_version" json:"ab_version,omitempty"`
	TrafficType       *string  `protobuf:"bytes,13,opt,name=traffic_type" json:"traffic_type,omitempty"`
	UtmSource         *string  `protobuf:"bytes,14,opt,name=utm_source" json:"utm_source,omitempty"`
	UtmMedium         *string  `protobuf:"bytes,15,opt,name=utm_medium" json:"utm_medium,omitempty"`
	UtmCampaign       *string  `protobuf:"bytes,16,opt,name=utm_campaign" json:"utm_campaign,omitempty"`
	ClientIp          *string  `protobuf:"bytes,17,opt,name=client_ip" json:"client_ip,omitempty"`
	DeviceBrand       *string  `protobuf:"bytes,18,opt,name=device_brand" json:"device_brand,omitempty"`
	OsApi             *uint32  `protobuf:"varint,19,opt,name=os_api" json:"os_api,omitempty"`
	Access            *string  `protobuf:"bytes,20,opt,name=access" json:"access,omitempty"`
	Language          *string  `protobuf:"bytes,21,opt,name=language" json:"language,omitempty"`
	Region            *string  `protobuf:"bytes,22,opt,name=region" json:"region,omitempty"`
	AppLanguage       *string  `protobuf:"bytes,23,opt,name=app_language" json:"app_language,omitempty"`
	AppRegion         *string  `protobuf:"bytes,24,opt,name=app_region" json:"app_region,omitempty"`
	CreativeId        *uint64  `protobuf:"varint,25,opt,name=creative_id" json:"creative_id,omitempty"`
	AdId              *uint64  `protobuf:"varint,26,opt,name=ad_id" json:"ad_id,omitempty"`
	CampaignId        *uint64  `protobuf:"varint,27,opt,name=campaign_id" json:"campaign_id,omitempty"`
	LogType           *string  `protobuf:"bytes,28,opt,name=log_type" json:"log_type,omitempty"`
	Rnd               *string  `protobuf:"bytes,29,opt,name=rnd" json:"rnd,omitempty"`
	Platform          *string  `protobuf:"bytes,30,opt,name=platform" json:"platform,omitempty"`
	SdkVersion        *string  `protobuf:"bytes,31,opt,name=sdk_version" json:"sdk_version,omitempty"`
	Province          *string  `protobuf:"bytes,32,opt,name=province" json:"province,omitempty"`
	City              *string  `protobuf:"bytes,33,opt,name=city" json:"city,omitempty"`
	Timezone          *int32   `protobuf:"varint,34,opt,name=timezone" json:"timezone,omitempty"`
	TzOffset          *int32   `protobuf:"varint,35,opt,name=tz_offset" json:"tz_offset,omitempty"`
	TzName            *string  `protobuf:"bytes,36,opt,name=tz_name" json:"tz_name,omitempty"`
	SimRegion         *string  `protobuf:"bytes,37,opt,name=sim_region" json:"sim_region,omitempty"`
	Carrier           *string  `protobuf:"bytes,38,opt,name=carrier" json:"carrier,omitempty"`
	Resolution        *string  `protobuf:"bytes,39,opt,name=resolution" json:"resolution,omitempty"`
	Browser           *string  `protobuf:"bytes,50,opt,name=browser" json:"browser,omitempty"`
	BrowserVersion    *string  `protobuf:"bytes,51,opt,name=browser_version" json:"browser_version,omitempty"`
	Referrer          *string  `protobuf:"bytes,52,opt,name=referrer" json:"referrer,omitempty"`
	ReferrerHost      *string  `protobuf:"bytes,53,opt,name=referrer_host" json:"referrer_host,omitempty"`
	ScreenHeight      *int32   `protobuf:"varint,54,opt,name=screen_height" json:"screen_height,omitempty"`
	ScreenWidth       *int32   `protobuf:"varint,55,opt,name=screen_width" json:"screen_width,omitempty"`
	Tz                *float32 `protobuf:"fixed32,56,opt,name=tz" json:"tz,omitempty"`
	AppVersionMinor   *string  `protobuf:"bytes,57,opt,name=app_version_minor" json:"app_version_minor,omitempty"`
	CarrierRegion     *string  `protobuf:"bytes,58,opt,name=carrier_region" json:"carrier_region,omitempty"`
	ProductName       *string  `protobuf:"bytes,59,opt,name=product_name" json:"product_name,omitempty"`
	ProductId         *uint32  `protobuf:"varint,60,opt,name=product_id" json:"product_id,omitempty"`
	Custom            *string  `protobuf:"bytes,61,opt,name=custom" json:"custom,omitempty"`
	UpdateVersionCode *uint32  `protobuf:"varint,62,opt,name=update_version_code" json:"update_version_code,omitempty"`
	AbSdkVersion      *string  `protobuf:"bytes,63,opt,name=ab_sdk_version" json:"ab_sdk_version,omitempty"`
	UserAgent         *string  `protobuf:"bytes,64,opt,name=user_agent" json:"user_agent,omitempty"`
	ClientPort        *uint32  `protobuf:"varint,65,opt,name=client_port" json:"client_port,omitempty"`
	DataCenter        *string  `protobuf:"bytes,66,opt,name=data_center" json:"data_center,omitempty"`
	OriginAppId       *uint32  `protobuf:"varint,67,opt,name=origin_app_id" json:"origin_app_id,omitempty"`
	OriginAppName     *string  `protobuf:"bytes,68,opt,name=origin_app_name" json:"origin_app_name,omitempty"`
	UtmTerm           *string  `protobuf:"bytes,69,opt,name=utm_term" json:"utm_term,omitempty"`
	UtmContent        *string  `protobuf:"bytes,70,opt,name=utm_content" json:"utm_content,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`

	AppAppId          *uint32  `protobuf:"varint,2,req,name=app_id" json:"aid,omitempty"`
	DeviceId		  *uint64  `protobuf:"varint,26,opt,name=ad_id" json:"device_id,omitempty"`
	SsId			  *string  `protobuf:"varint,26,opt,name=ad_id" json:"ssid,omitempty"`
	User_unique_id    *string  `protobuf:"varint,26,opt,name=ad_id" json:"user_unique_id,omitempty"`
	Install_id		  *uint64  `protobuf:"varint,26,opt,name=ad_id" json:"install_id,omitempty"`
	Web_id		  	  *uint64  `protobuf:"varint,26,opt,name=ad_id" json:"web_id,omitempty"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}

func (m *Header) GetHeaders() string {
	if m != nil && m.Headers != nil {
		return *m.Headers
	}
	return ""
}

func (m *Header) GetAppId() uint32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *Header) GetAppName() string {
	if m != nil && m.AppName != nil {
		return *m.AppName
	}
	return ""
}

func (m *Header) GetAppInstallId() uint64 {
	if m != nil && m.AppInstallId != nil {
		return *m.AppInstallId
	}
	return 0
}

func (m *Header) GetAppPackage() string {
	if m != nil && m.AppPackage != nil {
		return *m.AppPackage
	}
	return ""
}

func (m *Header) GetAppChannel() string {
	if m != nil && m.AppChannel != nil {
		return *m.AppChannel
	}
	return ""
}

func (m *Header) GetAppVersion() string {
	if m != nil && m.AppVersion != nil {
		return *m.AppVersion
	}
	return ""
}

func (m *Header) GetOsName() string {
	if m != nil && m.OsName != nil {
		return *m.OsName
	}
	return ""
}

func (m *Header) GetOsVersion() string {
	if m != nil && m.OsVersion != nil {
		return *m.OsVersion
	}
	return ""
}

func (m *Header) GetDeviceModel() string {
	if m != nil && m.DeviceModel != nil {
		return *m.DeviceModel
	}
	return ""
}

func (m *Header) GetAbClient() string {
	if m != nil && m.AbClient != nil {
		return *m.AbClient
	}
	return ""
}

func (m *Header) GetAbVersion() string {
	if m != nil && m.AbVersion != nil {
		return *m.AbVersion
	}
	return ""
}

func (m *Header) GetTrafficType() string {
	if m != nil && m.TrafficType != nil {
		return *m.TrafficType
	}
	return ""
}

func (m *Header) GetUtmSource() string {
	if m != nil && m.UtmSource != nil {
		return *m.UtmSource
	}
	return ""
}

func (m *Header) GetUtmMedium() string {
	if m != nil && m.UtmMedium != nil {
		return *m.UtmMedium
	}
	return ""
}

func (m *Header) GetUtmCampaign() string {
	if m != nil && m.UtmCampaign != nil {
		return *m.UtmCampaign
	}
	return ""
}

func (m *Header) GetClientIp() string {
	if m != nil && m.ClientIp != nil {
		return *m.ClientIp
	}
	return ""
}

func (m *Header) GetDeviceBrand() string {
	if m != nil && m.DeviceBrand != nil {
		return *m.DeviceBrand
	}
	return ""
}

func (m *Header) GetOsApi() uint32 {
	if m != nil && m.OsApi != nil {
		return *m.OsApi
	}
	return 0
}

func (m *Header) GetAccess() string {
	if m != nil && m.Access != nil {
		return *m.Access
	}
	return ""
}

func (m *Header) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *Header) GetRegion() string {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return ""
}

func (m *Header) GetAppLanguage() string {
	if m != nil && m.AppLanguage != nil {
		return *m.AppLanguage
	}
	return ""
}

func (m *Header) GetAppRegion() string {
	if m != nil && m.AppRegion != nil {
		return *m.AppRegion
	}
	return ""
}

func (m *Header) GetCreativeId() uint64 {
	if m != nil && m.CreativeId != nil {
		return *m.CreativeId
	}
	return 0
}

func (m *Header) GetAdId() uint64 {
	if m != nil && m.AdId != nil {
		return *m.AdId
	}
	return 0
}

func (m *Header) GetCampaignId() uint64 {
	if m != nil && m.CampaignId != nil {
		return *m.CampaignId
	}
	return 0
}

func (m *Header) GetLogType() string {
	if m != nil && m.LogType != nil {
		return *m.LogType
	}
	return ""
}

func (m *Header) GetRnd() string {
	if m != nil && m.Rnd != nil {
		return *m.Rnd
	}
	return ""
}

func (m *Header) GetPlatform() string {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ""
}

func (m *Header) GetSdkVersion() string {
	if m != nil && m.SdkVersion != nil {
		return *m.SdkVersion
	}
	return ""
}

func (m *Header) GetProvince() string {
	if m != nil && m.Province != nil {
		return *m.Province
	}
	return ""
}

func (m *Header) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *Header) GetTimezone() int32 {
	if m != nil && m.Timezone != nil {
		return *m.Timezone
	}
	return 0
}

func (m *Header) GetTzOffset() int32 {
	if m != nil && m.TzOffset != nil {
		return *m.TzOffset
	}
	return 0
}

func (m *Header) GetTzName() string {
	if m != nil && m.TzName != nil {
		return *m.TzName
	}
	return ""
}

func (m *Header) GetSimRegion() string {
	if m != nil && m.SimRegion != nil {
		return *m.SimRegion
	}
	return ""
}

func (m *Header) GetCarrier() string {
	if m != nil && m.Carrier != nil {
		return *m.Carrier
	}
	return ""
}

func (m *Header) GetResolution() string {
	if m != nil && m.Resolution != nil {
		return *m.Resolution
	}
	return ""
}

func (m *Header) GetBrowser() string {
	if m != nil && m.Browser != nil {
		return *m.Browser
	}
	return ""
}

func (m *Header) GetBrowserVersion() string {
	if m != nil && m.BrowserVersion != nil {
		return *m.BrowserVersion
	}
	return ""
}

func (m *Header) GetReferrer() string {
	if m != nil && m.Referrer != nil {
		return *m.Referrer
	}
	return ""
}

func (m *Header) GetReferrerHost() string {
	if m != nil && m.ReferrerHost != nil {
		return *m.ReferrerHost
	}
	return ""
}

func (m *Header) GetScreenHeight() int32 {
	if m != nil && m.ScreenHeight != nil {
		return *m.ScreenHeight
	}
	return 0
}

func (m *Header) GetScreenWidth() int32 {
	if m != nil && m.ScreenWidth != nil {
		return *m.ScreenWidth
	}
	return 0
}

func (m *Header) GetTz() float32 {
	if m != nil && m.Tz != nil {
		return *m.Tz
	}
	return 0
}

func (m *Header) GetAppVersionMinor() string {
	if m != nil && m.AppVersionMinor != nil {
		return *m.AppVersionMinor
	}
	return ""
}

func (m *Header) GetCarrierRegion() string {
	if m != nil && m.CarrierRegion != nil {
		return *m.CarrierRegion
	}
	return ""
}

func (m *Header) GetProductName() string {
	if m != nil && m.ProductName != nil {
		return *m.ProductName
	}
	return ""
}

func (m *Header) GetProductId() uint32 {
	if m != nil && m.ProductId != nil {
		return *m.ProductId
	}
	return 0
}

func (m *Header) GetCustom() string {
	if m != nil && m.Custom != nil {
		return *m.Custom
	}
	return ""
}

func (m *Header) GetUpdateVersionCode() uint32 {
	if m != nil && m.UpdateVersionCode != nil {
		return *m.UpdateVersionCode
	}
	return 0
}

func (m *Header) GetAbSdkVersion() string {
	if m != nil && m.AbSdkVersion != nil {
		return *m.AbSdkVersion
	}
	return ""
}

func (m *Header) GetUserAgent() string {
	if m != nil && m.UserAgent != nil {
		return *m.UserAgent
	}
	return ""
}

func (m *Header) GetClientPort() uint32 {
	if m != nil && m.ClientPort != nil {
		return *m.ClientPort
	}
	return 0
}

func (m *Header) GetDataCenter() string {
	if m != nil && m.DataCenter != nil {
		return *m.DataCenter
	}
	return ""
}

func (m *Header) GetOriginAppId() uint32 {
	if m != nil && m.OriginAppId != nil {
		return *m.OriginAppId
	}
	return 0
}

func (m *Header) GetOriginAppName() string {
	if m != nil && m.OriginAppName != nil {
		return *m.OriginAppName
	}
	return ""
}

func (m *Header) GetUtmTerm() string {
	if m != nil && m.UtmTerm != nil {
		return *m.UtmTerm
	}
	return ""
}

func (m *Header) GetUtmContent() string {
	if m != nil && m.UtmContent != nil {
		return *m.UtmContent
	}
	return ""
}

type Event struct {
	Event            *string `protobuf:"bytes,3,req,name=event" json:"event,omitempty"`
	Time             *uint32 `protobuf:"varint,4,req,name=time" json:"time,omitempty"`
	Params           interface{} `protobuf:"bytes,5,req,name=params" json:"params,omitempty"`
	SessionId        *string `protobuf:"bytes,6,opt,name=session_id" json:"session_id,omitempty"`
	LocalTimeMs      *uint64 `protobuf:"varint,7,opt,name=local_time_ms" json:"local_time_ms,omitempty"`
	XStagingFlag     *bool   `protobuf:"varint,8,opt,name=_staging_flag" json:"_staging_flag,omitempty"`
	SeqId            *uint32 `protobuf:"varint,9,opt,name=seq_id" json:"seq_id,omitempty"`
	EventId          *uint64 `protobuf:"varint,10,opt,name=event_id" json:"event_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`

	Datetime      	 *string `protobuf:"bytes,3,req,name=event" json:"datetime,omitempty"`
	UserId      	 *string `protobuf:"bytes,3,req,name=event" json:"user_id,omitempty"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}

func (m *Event) GetEvent() string {
	if m != nil && m.Event != nil {
		return *m.Event
	}
	return ""
}

func (m *Event) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Event) GetParams() interface{} {
	if m != nil && m.Params != nil {
		return m.Params
	}
	return ""
}

func (m *Event) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *Event) GetLocalTimeMs() uint64 {
	if m != nil && m.LocalTimeMs != nil {
		return *m.LocalTimeMs
	}
	return 0
}

func (m *Event) GetXStagingFlag() bool {
	if m != nil && m.XStagingFlag != nil {
		return *m.XStagingFlag
	}
	return false
}

func (m *Event) GetSeqId() uint32 {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return 0
}

func (m *Event) GetEventId() uint64 {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return 0
}

type MarioEvents struct {
	Caller           *string  `protobuf:"bytes,1,req,name=caller" json:"caller,omitempty"`
	ServerTime       *uint32  `protobuf:"varint,2,req,name=server_time" json:"server_time,omitempty"`
	User             *User    `protobuf:"bytes,3,req,name=user" json:"user,omitempty"`
	Header           *Header  `protobuf:"bytes,4,req,name=header" json:"header,omitempty"`
	Events           []*Event `protobuf:"bytes,5,rep,name=events" json:"events,omitempty"`
	TraceId          *string  `protobuf:"bytes,6,opt,name=trace_id" json:"trace_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
	AppEvents        []*Event `protobuf:"bytes,5,rep,name=events" json:"event_v3,omitempty"`
}

func (m *MarioEvents) Reset()         { *m = MarioEvents{} }
func (m *MarioEvents) String() string { return proto.CompactTextString(m) }
func (*MarioEvents) ProtoMessage()    {}

func (m *MarioEvents) GetCaller() string {
	if m != nil && m.Caller != nil {
		return *m.Caller
	}
	return ""
}

func (m *MarioEvents) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *MarioEvents) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *MarioEvents) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MarioEvents) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *MarioEvents) GetTraceId() string {
	if m != nil && m.TraceId != nil {
		return *m.TraceId
	}
	return ""
}
